version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: |
           echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
           docker image build -t adisornwatt/circle .
           docker image push adisornwatt/circle
workflows:
    build-and-test:
      jobs:
        - build-and-test
